" settings for MacVim
"
" set initial window size
set lines=54
set columns=125
" set font
set gfn=Consolas:h12.00
" see `:help guioptions ` for more info
set guioptions=egmLtc

" ** Clojure **
let clj_highlight_builtins = 1
let clj_highlight_contrib = 1
let clj_paren_rainbow = 1
let clj_want_gorilla = 1
let vimclojure#NailgunClient="/usr/local/bin/ng"

" ** Fuzzy Finder **
let g:fuf_coveragefile_exclude = '\v\~$|\.(jar|class|o|exe|dll|bak|orig|sw[po])$|(^|[/\\])\.(hg|git|bzr)($|[/\\])'

" filetype specific highlighting
hi scalaMethodCall gui=italic
