" settings for MacVim
" set the colors up nicely - slate theme
colorscheme github
" highlighting
set cursorline
" set initial window size
set lines=70
set columns=135
" set font
set gfn=Panic\ Sans:h11.00
" set some transparency
set transparency=10
