" settings for MacVim
" set the colors up nicely - slate theme
colorscheme github
" highlighting
set cursorline
" set initial window size
set lines=63
set columns=124
" set font
set gfn=Panic\ Sans:h11.00
" set some transparency
set transparency=10
" remove toolbar
set guioptions-=T

" ** Clojure **
let clj_highlight_builtins = 1
let clj_highlight_contrib = 1
let clj_paren_rainbow = 1
let clj_want_gorilla = 1
let vimclojure#NailgunClient="/usr/local/bin/ng"

" ** Fuzzy Finder **
let g:fuf_coveragefile_exclude = '\v\~$|\.(jar|class|o|exe|dll|bak|orig|sw[po])$|(^|[/\\])\.(hg|git|bzr)($|[/\\])'

" filetype specific highlighting
hi scalaMethodCall gui=italic
