" run pathogen
call pathogen#infect()
" first the disabled features due to security concerns
set modelines=0 " no modelines [http://www.guninski.com/vim1.html]
" let vim know background of terminal is dark
if has('gui_running')
  set background=light
else
  let g:solarized_termtrans=10
  set background=dark
endif
colorscheme solarized

" set the leader key for commands
let mapleader = ","
let maplocalleader = ";"

" map shortcuts
" shortcuts for fuzzyfinder plugin
map <leader>f :FufFile<CR>
map <leader>b :FufBuffer<CR>
" shortcut for fuzzyfinder_textmate
map <leader>t :FufCoverageFile<CR>
" shortcuts for vtreeexplorer plugin
map <leader>d :VSTreeExplore<CR>
" enables cmd-# to switch between tabs
map <D-1> :tabn1<CR>
map <D-2> :tabn2<CR>
map <D-3> :tabn3<CR>
map <D-4> :tabn4<CR>
map <D-5> :tabn5<CR>
map <D-6> :tabn6<CR>
map <D-7> :tabn7<CR>
map <D-8> :tabn8<CR>
map <D-9> :tabn9<CR>
map <D-0> :tabn10<CR>
" tab navigation
map <C-n> :tabn<CR>
map <C-p> :tabp<CR>
" easier split navigation
map <down> <C-w><down>
map <up> <C-w><up>
map <left> <C-w><left>
map <right> <C-w><right>
map <D-H> <C-w><left>
" shortcuts for javascript ftplugin
map <leader>jsff zE:JavaScriptFoldFunctions<CR>
function! ShowSyntax()
	for id in synstack(line("."), col("."))
		echo synIDattr(id,"name")
	endfor
endfunction
map <F10> :call ShowSyntax()<CR>

" general settings
" backup files to the .vim directory rather than the current directory
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp
" show line numbers and ruler all the time
set number
set ruler
" search ignores case and doesn't highlight all finds
set ignorecase
set nohlsearch
set incsearch
" tabwidth = 2 spaces
set ts=2
set shiftwidth=2
set expandtab
" set fold method to manual
set foldmethod=manual
" set acceptable file formats
set ffs=unix,dos
" autoindent please
set autoindent

" allow for filetype specific things
filetype plugin on
syntax on

" Tree Explorer plugin - vtreeexplorer
let treeExplVertical=1
let treeExplWinSize=40

" blogging - vimblog
let g:blogconfig = "~/.vimblogconfig"

" allow project specific vim settings
if filereadable("./.project.vimrc")
  source ./.project.vimrc
endif
set exrc
set secure
