" This must be first, because it changes other options as side effect
set nocompatible
" run pathogen
call pathogen#helptags()
call pathogen#infect()
" Allow buffer changes to persist in background (without saving first)
set hidden
" first the disabled features due to security concerns
set modelines=0 " no modelines [http://www.guninski.com/vim1.html]
" do not show mode information in message line
set noshowmode
" let vim know background of terminal is dark
if has('gui_running')
  set background=light " Always light for now
else
  "set background=dark
  set background=light " Always light for now
endif
colorscheme solarized

" set backspace permissions
set backspace=indent,eol,start
" reduce leader timeout from 1000ms
set timeoutlen=350
" map shortcuts
" enables cmd-# to switch between tabs
map <D-1> :tabn1<CR>
map <D-2> :tabn2<CR>
map <D-3> :tabn3<CR>
map <D-4> :tabn4<CR>
map <D-5> :tabn5<CR>
map <D-6> :tabn6<CR>
map <D-7> :tabn7<CR>
map <D-8> :tabn8<CR>
map <D-9> :tabn9<CR>
map <D-0> :tabn10<CR>
" relative line numbers
map <D-r> :set relativenumber<CR>
map <D-R> :set norelativenumber<CR>
" easier split navigation
map <down> <C-w><down>
map <up> <C-w><up>
map <left> <C-w><left>
map <right> <C-w><right>
map <D-H> <C-w><left>
" shortcuts for javascript and PHP ftplugin
map <leader>zff zE:FoldFunctions<CR>
function! ShowSyntax()
  for id in synstack(line("."), col("."))
    echo synIDattr(id,"name")
  endfor
endfunction
map <F10> :call ShowSyntax()<CR>
" Mapping to regenerate tags with `ctags`
map <Leader>rt :!ctags -R --exclude=.git<CR><CR>

" general settings
" backup files to the .vim directory rather than the current directory
set nobackup
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim/tmp
set writebackup
" show line numbers and ruler all the time
set number
set ruler
" highlight line of cursor
set cursorline
" highlight matching [{()}]
set showmatch
" search ignores case and doesn't highlight all finds
set nohlsearch
set incsearch
" tabwidth = 2 spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
" set fold method to marker
set foldmethod=marker
" set acceptable file formats
set ffs=unix,dos
" autoindent please
set autoindent
" wildignore
set wildignore+=tmp/*,node_modules/*,vendor/rails/*,vendor/gems/*
set wildignore+=vendor/plugins/*,src/main/webapp/WEB-INF/classes/*
set wildignore+=*.so,*.swp,*.zip,*.jpg,*.png,*.gif
" show whitespace in a useful way
set list
set listchars=tab:>.

" Make it possible to disable autoindent and stuff when pasting
set pastetoggle=<F2>

" allow for filetype specific things
filetype on
filetype plugin on
syntax on

" Allow Project specific vimrc
set exrc
set secure

" ** Plugin Mappings ** "
map <leader>u :GundoToggle<CR>
" Show line numbers on netrw directory listings
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'

source $DOTCONFIG/vim/conf/lightline.vim
source $DOTCONFIG/vim/conf/ctrlp.vim
