" Change the <leader> to <space>
let mapleader = " "
" This must be first, because it changes other options as side effect
set nocompatible
" run pathogen
call pathogen#helptags()
call pathogen#infect()
" Allow buffer changes to persist in background (without saving first)
set hidden
" first the disabled features due to security concerns
set modelines=0 " no modelines [http://www.guninski.com/vim1.html]
" do not show mode information in message line
set noshowmode
" let vim know background of terminal is dark
if has('gui_running')
  set background=light " Always light for now
else
  "set background=dark
  set background=light " Always light for now
endif
colorscheme solarized

" set backspace permissions
set backspace=indent,eol,start
" reduce leader timeout from 1000ms
set timeoutlen=350
" shortcuts for javascript and PHP ftplugin
map <leader>zff zE:FoldFunctions<CR>
function! ShowSyntax()
  for id in synstack(line("."), col("."))
    echo synIDattr(id,"name")
  endfor
endfunction
map <F10> :call ShowSyntax()<CR>

" general settings
" backup files to the .vim directory rather than the current directory
set nobackup
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim/tmp
set writebackup
" show line numbers and ruler all the time
set number
set ruler
" highlight line of cursor
set cursorline
" highlight matching [{()}]
set showmatch
" search doesn't highlight all finds
set nohlsearch
" search ignores case
set incsearch
" tabwidth = 2 spaces (this may be overriden by editorconfig)
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
" set fold method to marker
set foldmethod=marker
" set acceptable file formats
set ffs=unix,dos
" autoindent please
set autoindent
" wildignore - don't show these files when expanding globs
set wildignore+=tmp/*,node_modules/*,vendor/rails/*,vendor/gems/*
set wildignore+=vendor/plugins/*,src/main/webapp/WEB-INF/classes/*
set wildignore+=*.so,*.swp,*.zip,*.jpg,*.png,*.gif,*.class
" show whitespace in a useful way
set list
set listchars=tab:>.

" Make it possible to disable autoindent and stuff when pasting
set pastetoggle=<F2>

" allow for filetype specific things
filetype on
filetype plugin on
syntax on

" Allow Project specific vimrc
set exrc
set secure

" ** Plugin Mappings ** "
" Show line numbers on netrw directory listings
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'
let g:polyglot_disabled = ['git']

source $DOTCONFIG/vim/conf/lightline.vim
source $DOTCONFIG/vim/conf/ctrlp.vim
source $DOTCONFIG/vim/conf/fzf.vim
source $DOTCONFIG/vim/conf/jsx.vim
source $DOTCONFIG/vim/conf/lsp.vim
source $DOTCONFIG/vim/conf/ruby.vim
source $DOTCONFIG/vim/conf/rust.vim
source $DOTCONFIG/vim/conf/typescript.vim
source $DOTCONFIG/vim/conf/vista.vim

source $DOTCONFIG/vim/conf/keymap.vim
