[aws]
symbol = "☁ "
displayed_items = "profile"

[battery]
format = '[$percentage]($style) '

[nodejs]
symbol = "⬢ "
style = "green"

[git_status]
format = '([\[$conflicted$modified$staged$untracked$ahead_behind\]]($style) )'
modified = "*"
style = "bold red"

[package]
disabled = true

[time]
disabled = false
