[aws]
symbol = "☁ "
# format = 'on [$symbol($profile )(\($region\) )]($style)' # default
format = 'on [$symbol($profile )]($style)'

[battery]
format = '[$percentage]($style) '

[docker_context]
disabled = true

[kotlin]
disabled = true

[nodejs]
symbol = "⬢ "
style = "green"

[git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )' # default
format = '([\[$conflicted$modified$staged$untracked$ahead_behind\]]($style) )'
modified = "*"
style = "bold red"

[gradle]
disabled = true

[package]
disabled = true

[time]
disabled = false
